services:
  app:
    image:  mstarman/chem-converter-test:0.0.4
    build: .
    env_file:
      - ./.env
    ports: # expose default rails port to host machine
      - ${PROJECT_WEB_PORT:-4000}:80
    volumes:
      - ./converter/profiles/profiles:/var/share/profiles
      - ./converter/datasets:/var/share/datasets
      - ./converter/logs:/var/log/converter
      - ./converter/htpasswd:/var/share/htpasswd
      - ./converter/shell_scripts:/shell_scripts
      - ./converter/CLIENT_BRANCH.txt:/var/share/CLIENT_BRANCH.txt
      - ./converter/APP_BRANCH.txt:/var/share/APP_BRANCH.txt